name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint --if-present

    - name: Run Tests
      run: npm test --if-present

    - name: Build project
      run: npm run build --if-present

    - name: Upload production build
      uses: actions/upload-artifact@v3
      with:
        name: production-build
        path: build
